import Head from "next/head";
import Image from "next/image";
import bgmovil from "/public/bg-intro-mobile.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className="h-[1000px] flex flex-col justify-around  relative">
        <Image
          src={bgmovil}
          alt="bg-intro-pic"
          className="absolute z-10"
        ></Image>
        <div className="absolute bg-[#FF7A7A] w-[100%] h-[100%] z-0"></div>

        <div className="z-20 absolute p-5 flex flex-col gap-10">
          <div className="text-center text-white pb-2">
            <h1 className="mb-4 font-bold text-xl px-20">
              Learn to code by watching others
            </h1>
            <p className="px-3">
              See how experienced developers solve problems in real-time.
              Watching scripted tutorials is great, but understanding how
              developers think is invaluable.
            </p>
          </div>
          <div className="flex flex-col gap-4 shadow-personal">
            <div className="bg-[#6055A5] py-4 px-12 rounded-lg text-center text-white shadow-personal">
              <span className="font-semibold">Try it free 7 days</span>
              <span className="text-white/50"> then $20/mo. thereafter</span>
            </div>
            <div className="bg-white p-4 rounded-md flex flex-col gap-4 ">
              {["First Name", "Last Name", "Email", "Address", "Password"].map(
                (name) => (
                  <div key={name} className="border-2 p-3 rounded-md">
                    {name}
                  </div>
                )
              )}
              <button className="bg-[#38CC8C] text-center p-3 rounded-md text-white uppercase">
                Claim your free trial
              </button>
              <h4 className=" text-center text-xs p-3 text-black/30">
                By clicking the button, you are agreeing to our
                <span className="ml-1 text-red-600 font-semibold">
                  Terms and Services
                </span>
              </h4>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
