import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useBreakpoint } from "../hooks/useBreakpoint";
import bgmovil from "/public/bg-intro-mobile.png";
import bgdesktop from "/public/bg-intro-desktop.png";

export default function Home() {
  const breakpoint = useBreakpoint();
  const bgImage = breakpoint.xl == true ? bgdesktop : bgmovil;

  function handleFirstNameInput(event: React.MouseEvent<HTMLButtonElement>) {
    event.preventDefault();
    const [inputs, labels, icons] = [
      document.querySelectorAll("input"),
      document.querySelectorAll("label"),
      document.getElementsByClassName("ErrorIcon"),
    ];

    {
      inputs.forEach((input, indx) => {
        if (input.value == "") {
          input.classList.add("border-red-500");
          input.value = "";
          input.placeholder = "";

          icons[indx].classList.remove("hidden");
          icons[indx].classList.add("block");
        }
        if (input.id == "Email Address" && !input.validity.valid) {
          input.placeholder = "email@example/com";
          input.classList.add("placeholder:text-red-500/50");
          input.classList.add("text-xs");
          input.classList.add("pl-5");
          input.value = "";

          icons[indx].classList.remove("hidden");
          icons[indx].classList.add("block");
        }
      });
    }
  }
  function errorIconClick(event: React.MouseEvent<HTMLImageElement>) {
    const labels = document.querySelectorAll("label");
    const iconos = document.getElementsByClassName("ErrorIcon");

    Array.from(iconos).map((icn, indx) => {
      if (icn == event.target) {
        if (labels[indx].classList.contains("text-white")) {
          labels[indx].classList.remove("text-white");
          labels[indx].classList.add("text-red-500");
        } else {
          labels[indx].classList.add("text-white");
          labels[indx].classList.remove("text-red-500");
        }
      }
    });
  }
  function ClearInput(event: React.FocusEvent<HTMLInputElement>) {
    const [inputs, labels, icons] = [
      document.querySelectorAll("input"),
      document.querySelectorAll("label"),
      document.getElementsByClassName("ErrorIcon"),
    ];
    inputs.forEach((input, indx) => {
      if (input == event.currentTarget) {
        input.classList.remove("border-red-500");
        input.classList.add("border-gray-300");
        if (input.id == "Email Address") {
          input.classList.remove("placeholder:text-red-500/50");
          input.classList.remove("text-xs");
          input.classList.remove("pl-5");
          input.classList.add("placeholder:text-black/1");
          input.classList.add("text-base");
          input.classList.add("pl-3");
        }
        input.placeholder = input.id;
        labels[indx].classList.add("text-white");
        labels[indx].classList.remove("text-red-500");
        icons[indx].classList.add("hidden");
        icons[indx].classList.remove("block");
      }
    });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className="h-[1000px]  xl:h-[100%] xl:w-[100%] flex flex-col justify-around  relative">
        <Image
          src={bgImage}
          alt="bg-intro-pic"
          className="absolute z-10 xl:h-[100%] xl:w-[100%]"
        ></Image>
        <div className="absolute bg-[#FF7A7A] w-[100%] h-[100%] z-0"></div>

        <div className="z-20 w-full top-[10%] xl:top-[20%] xl:left-[15%] xl:h-[60%] xl:w-[70%] absolute px-5 xl:px-0 flex flex-col xl:flex-row gap-14">
          <div className="text-center xl:text-left text-white pb-2 mt-3 xl:mt-0 xl:w-[50%] xl:flex xl:flex-col xl:justify-center">
            <h1 className="mb-8 font-bold text-2xl px-10 xl:px-0 xl:text-5xl">
              Learn to code by watching others
            </h1>
            <p className="px-3 xl:px-0 leading-relaxed">
              See how experienced developers solve problems in real-time.
              Watching scripted tutorials is great, but understanding how
              developers think is invaluable.
            </p>
          </div>
          <div className="flex flex-col gap-5 xl:gap-6 xl:w-[50%] ">
            <div className="bg-[#6055A5] py-6 px-12 xl:py-4 rounded-lg text-center text-white shadow-personal">
              <span className="font-semibold">Try it free 7 days</span>
              <span className="text-white/50"> then $20/mo. thereafter</span>
            </div>
            <div className="bg-white p-4 xl:p-10 xl:px-10 rounded-md flex flex-col shadow-personal gap-2 xl:gap-0">
              <form
                action=""
                method="post"
                className="flex flex-col gap-2 xl:gap-0 text-black "
              >
                <div className="flex flex-col relative">
                  <input
                    type="text"
                    name="First Name"
                    id="First Name"
                    placeholder="First Name"
                    required
                    className="border-2 p-3 rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm border-gray-300 font-semibold "
                    onFocus={ClearInput}
                  />
                  <label
                    htmlFor="First Name"
                    id="FirstNameLabel"
                    className="text-[0.6rem] text-white place-self-end"
                  >
                    First Name cannot be empty
                  </label>
                  <Image
                    src="/icon-error.svg"
                    alt=""
                    width={24}
                    height={24}
                    className="absolute top-[20%] right-4 hidden  ErrorIcon"
                    onClick={errorIconClick}
                  ></Image>
                </div>
                <div className="flex flex-col relative">
                  <input
                    type="text"
                    name="Last Name"
                    id="Last Name"
                    placeholder="Last Name"
                    required
                    onFocus={ClearInput}
                    className="border-2 p-3 rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm border-gray-300 font-semibold"
                  />
                  <label
                    htmlFor="Last Name"
                    className="text-[0.6rem] text-white place-self-end"
                  >
                    Last Name cannot be empty
                  </label>
                  <Image
                    src="/icon-error.svg"
                    alt=""
                    width={24}
                    height={24}
                    onClick={errorIconClick}
                    className="absolute top-[20%] right-4 hidden  ErrorIcon"
                  ></Image>
                </div>
                <div className="flex flex-col relative">
                  <input
                    type="email"
                    name="Email Address"
                    id="Email Address"
                    placeholder="Email Address"
                    required
                    pattern="^[^\s@]+@[^\s@]+\.[^\s@]+$"
                    onFocus={ClearInput}
                    className="border-2 p-3 rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full h-[52px] shadow-sm border-gray-300 font-semibold"
                  />
                  <label
                    htmlFor="Email Address"
                    className="text-[0.6rem] text-white place-self-end"
                  >
                    Looks like this is not an email
                  </label>
                  <Image
                    src="/icon-error.svg"
                    alt=""
                    width={24}
                    height={24}
                    onClick={errorIconClick}
                    className="absolute top-[20%] right-4 hidden ErrorIcon"
                  ></Image>
                </div>
                <div className="flex flex-col relative">
                  <input
                    type="password"
                    name="Password"
                    id="Password"
                    placeholder="Password"
                    required
                    onFocus={ClearInput}
                    className="border-2 p-3 rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm border-gray-300 font-semibold"
                  />
                  <label
                    htmlFor="Password"
                    className="text-[0.6rem] text-white place-self-end"
                  >
                    Password cannot be empty
                  </label>
                  <Image
                    src="/icon-error.svg"
                    alt=""
                    width={24}
                    height={24}
                    onClick={errorIconClick}
                    className="absolute top-[20%] right-4 hidden ErrorIcon"
                  ></Image>
                </div>
                <div className="flex flex-col shadow-md">
                  <button
                    type="submit"
                    className="bg-[#38CC8C] border-b-4 border-[#258b5f] text-center p-3 rounded-md text-white uppercase hover:bg-[#73f4bc] hover:border-[#33c083]"
                    onClick={handleFirstNameInput}
                  >
                    Claim your free trial
                  </button>
                </div>
              </form>
              <h4 className=" text-center text-xs p-3 text-black/30 mt-2">
                By clicking the button, you are agreeing to our
                <span className="ml-1 text-red-600 font-semibold">
                  Terms and Services
                </span>
              </h4>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
